# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Avoid buffering
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install dependencies
COPY pyproject.toml .
RUN pip install --no-cache-dir fastmcp>=2.10.0 httpx>=0.25.0 pycryptodome>=3.19.0

# Copy project files
COPY . .

# Start the MCP server
CMD ["python", "kisti-mcp-server.py"]
